//https://www.basketball-reference.com/playoffs/
//All NBA / ABA Champions

[
  {
    "": "Year",
    "__1": "Lg",
    "__2": "Champion",
    "__3": "Runner-Up",
    "__4": "Finals MVP",
    "Top Performers": "Points",
    "Top Performers__1": "Rebounds",
    "Top Performers__2": "Assists",
    "Top Performers__3": "Win Shares"
  },
  {
    "": 2019,
    "__1": "NBA",
    "__2": "Toronto Raptors",
    "__3": "Golden State Warriors",
    "__4": "K. Leonard",
    "Top Performers": "K. Leonard (732)",
    "Top Performers__1": "D. Green (223)",
    "Top Performers__2": "D. Green (187)",
    "Top Performers__3": "K. Leonard (4.9)"
  },
  {
    "": 2018,
    "__1": "NBA",
    "__2": "Golden State Warriors",
    "__3": "Cleveland Cavaliers",
    "__4": "K. Durant",
    "Top Performers": "L. James (748)",
    "Top Performers__1": "D. Green (222)",
    "Top Performers__2": "L. James (198)",
    "Top Performers__3": "L. James (5.2)"
  },
  {
    "": 2017,
    "__1": "NBA",
    "__2": "Golden State Warriors",
    "__3": "Cleveland Cavaliers",
    "__4": "K. Durant",
    "Top Performers": "L. James (591)",
    "Top Performers__1": "K. Love (191)",
    "Top Performers__2": "L. James (141)",
    "Top Performers__3": "L. James (4.3)"
  },
  {
    "": 2016,
    "__1": "NBA",
    "__2": "Cleveland Cavaliers",
    "__3": "Golden State Warriors",
    "__4": "L. James",
    "Top Performers": "K. Thompson (582)",
    "Top Performers__1": "D. Green (228)",
    "Top Performers__2": "R. Westbrook (198)",
    "Top Performers__3": "L. James (4.7)"
  },
  {
    "": 2015,
    "__1": "NBA",
    "__2": "Golden State Warriors",
    "__3": "Cleveland Cavaliers",
    "__4": "A. Iguodala",
    "Top Performers": "L. James (601)",
    "Top Performers__1": "D. Howard (238)",
    "Top Performers__2": "L. James (169)",
    "Top Performers__3": "S. Curry (3.9)"
  },
  {
    "": 2014,
    "__1": "NBA",
    "__2": "San Antonio Spurs",
    "__3": "Miami Heat",
    "__4": "K. Leonard",
    "Top Performers": "K. Durant (563)",
    "Top Performers__1": "T. Duncan (211)",
    "Top Performers__2": "R. Westbrook (153)",
    "Top Performers__3": "L. James (4.3)"
  },
  {
    "": 2013,
    "__1": "NBA",
    "__2": "Miami Heat",
    "__3": "San Antonio Spurs",
    "__4": "L. James",
    "Top Performers": "L. James (596)",
    "Top Performers__1": "T. Duncan (214)",
    "Top Performers__2": "L. James (152)",
    "Top Performers__3": "L. James (5.2)"
  },
  {
    "": 2012,
    "__1": "NBA",
    "__2": "Miami Heat",
    "__3": "Oklahoma City Thunder",
    "__4": "L. James",
    "Top Performers": "L. James (697)",
    "Top Performers__1": "L. James (224)",
    "Top Performers__2": "R. Rondo (227)",
    "Top Performers__3": "L. James (5.8)"
  },
  {
    "": 2011,
    "__1": "NBA",
    "__2": "Dallas Mavericks",
    "__3": "Miami Heat",
    "__4": "D. Nowitzki",
    "Top Performers": "D. Nowitzki (582)",
    "Top Performers__1": "T. Chandler (193)",
    "Top Performers__2": "J. Kidd (153)",
    "Top Performers__3": "L. James (3.8)"
  },
  {
    "": 2010,
    "__1": "NBA",
    "__2": "Los Angeles Lakers",
    "__3": "Boston Celtics",
    "__4": "K. Bryant",
    "Top Performers": "K. Bryant (671)",
    "Top Performers__1": "P. Gasol (255)",
    "Top Performers__2": "R. Rondo (223)",
    "Top Performers__3": "P. Gasol (4.3)"
  },
  {
    "": 2009,
    "__1": "NBA",
    "__2": "Los Angeles Lakers",
    "__3": "Orlando Magic",
    "__4": "K. Bryant",
    "Top Performers": "K. Bryant (695)",
    "Top Performers__1": "D. Howard (353)",
    "Top Performers__2": "R. Rondo (137)",
    "Top Performers__3": "L. James (4.8)"
  },
  {
    "": 2008,
    "__1": "NBA",
    "__2": "Boston Celtics",
    "__3": "Los Angeles Lakers",
    "__4": "P. Pierce",
    "Top Performers": "K. Bryant (633)",
    "Top Performers__1": "K. Garnett (274)",
    "Top Performers__2": "R. Rondo (172)",
    "Top Performers__3": "K. Garnett (4.1)"
  },
  {
    "": 2007,
    "__1": "NBA",
    "__2": "San Antonio Spurs",
    "__3": "Cleveland Cavaliers",
    "__4": "T. Parker",
    "Top Performers": "L. James (501)",
    "Top Performers__1": "T. Duncan (229)",
    "Top Performers__2": "L. James (159)",
    "Top Performers__3": "L. James (3.7)"
  },
  {
    "": 2006,
    "__1": "NBA",
    "__2": "Miami Heat",
    "__3": "Dallas Mavericks",
    "__4": "D. Wade",
    "Top Performers": "D. Wade (654)",
    "Top Performers__1": "D. Nowitzki (268)",
    "Top Performers__2": "S. Nash (204)",
    "Top Performers__3": "D. Nowitzki (5.4)"
  },
  {
    "": 2005,
    "__1": "NBA",
    "__2": "San Antonio Spurs",
    "__3": "Detroit Pistons",
    "__4": "T. Duncan",
    "Top Performers": "T. Duncan (542)",
    "Top Performers__1": "T. Duncan (286)",
    "Top Performers__2": "S. Nash (170)",
    "Top Performers__3": "C. Billups (4.6)"
  },
  {
    "": 2004,
    "__1": "NBA",
    "__2": "Detroit Pistons",
    "__3": "Los Angeles Lakers",
    "__4": "C. Billups",
    "Top Performers": "K. Bryant (539)",
    "Top Performers__1": "B. Wallace (328)",
    "Top Performers__2": "C. Billups (136)",
    "Top Performers__3": "S. O'Neal (3.9)"
  },
  {
    "": 2003,
    "__1": "NBA",
    "__2": "San Antonio Spurs",
    "__3": "New Jersey Nets",
    "__4": "T. Duncan",
    "Top Performers": "T. Duncan (593)",
    "Top Performers__1": "T. Duncan (369)",
    "Top Performers__2": "J. Kidd (163)",
    "Top Performers__3": "T. Duncan (5.9)"
  },
  {
    "": 2002,
    "__1": "NBA",
    "__2": "Los Angeles Lakers",
    "__3": "New Jersey Nets",
    "__4": "S. O'Neal",
    "Top Performers": "S. O'Neal (541)",
    "Top Performers__1": "S. O'Neal (239)",
    "Top Performers__2": "J. Kidd (182)",
    "Top Performers__3": "S. O'Neal (3.8)"
  },
  {
    "": 2001,
    "__1": "NBA",
    "__2": "Los Angeles Lakers",
    "__3": "Philadelphia 76ers",
    "__4": "S. O'Neal",
    "Top Performers": "A. Iverson (723)",
    "Top Performers__1": "D. Mutombo (316)",
    "Top Performers__2": "A. Iverson (134)",
    "Top Performers__3": "K. Bryant (3.8)"
  },
  {
    "": 2000,
    "__1": "NBA",
    "__2": "Los Angeles Lakers",
    "__3": "Indiana Pacers",
    "__4": "S. O'Neal",
    "Top Performers": "S. O'Neal (707)",
    "Top Performers__1": "S. O'Neal (355)",
    "Top Performers__2": "M. Jackson (178)",
    "Top Performers__3": "S. O'Neal (4.7)"
  },
  {
    "": 1999,
    "__1": "NBA",
    "__2": "San Antonio Spurs",
    "__3": "New York Knicks",
    "__4": "T. Duncan",
    "Top Performers": "L. Sprewell (407)",
    "Top Performers__1": "T. Duncan (195)",
    "Top Performers__2": "A. Johnson (126)",
    "Top Performers__3": "T. Duncan (3.7)"
  },
  {
    "": 1998,
    "__1": "NBA",
    "__2": "Chicago Bulls",
    "__3": "Utah Jazz",
    "__4": "M. Jordan",
    "Top Performers": "M. Jordan (680)",
    "Top Performers__1": "D. Rodman (248)",
    "Top Performers__2": "J. Stockton (155)",
    "Top Performers__3": "M. Jordan (4.8)"
  },
  {
    "": 1997,
    "__1": "NBA",
    "__2": "Chicago Bulls",
    "__3": "Utah Jazz",
    "__4": "M. Jordan",
    "Top Performers": "M. Jordan (590)",
    "Top Performers__1": "K. Malone (228)",
    "Top Performers__2": "J. Stockton (191)",
    "Top Performers__3": "M. Jordan (3.9)"
  },
  {
    "": 1996,
    "__1": "NBA",
    "__2": "Chicago Bulls",
    "__3": "Seattle SuperSonics",
    "__4": "M. Jordan",
    "Top Performers": "M. Jordan (552)",
    "Top Performers__1": "D. Rodman (247)",
    "Top Performers__2": "J. Stockton (195)",
    "Top Performers__3": "M. Jordan (4.7)"
  },
  {
    "": 1995,
    "__1": "NBA",
    "__2": "Houston Rockets",
    "__3": "Orlando Magic",
    "__4": "H. Olajuwon",
    "Top Performers": "H. Olajuwon (725)",
    "Top Performers__1": "S. O'Neal (250)",
    "Top Performers__2": "A. Hardaway (162)",
    "Top Performers__3": "S. O'Neal (3.0)"
  },
  {
    "": 1994,
    "__1": "NBA",
    "__2": "Houston Rockets",
    "__3": "New York Knicks",
    "__4": "H. Olajuwon",
    "Top Performers": "H. Olajuwon (664)",
    "Top Performers__1": "P. Ewing (293)",
    "Top Performers__2": "J. Stockton (157)",
    "Top Performers__3": "H. Olajuwon (4.3)"
  },
  {
    "": 1993,
    "__1": "NBA",
    "__2": "Chicago Bulls",
    "__3": "Phoenix Suns",
    "__4": "M. Jordan",
    "Top Performers": "M. Jordan (666)",
    "Top Performers__1": "C. Barkley (326)",
    "Top Performers__2": "K. Johnson (182)",
    "Top Performers__3": "C. Barkley (4.6)"
  },
  {
    "": 1992,
    "__1": "NBA",
    "__2": "Chicago Bulls",
    "__3": "Portland Trail Blazers",
    "__4": "M. Jordan",
    "Top Performers": "M. Jordan (759)",
    "Top Performers__1": "H. Grant (194)",
    "Top Performers__2": "J. Stockton (217)",
    "Top Performers__3": "M. Jordan (4.1)"
  },
  {
    "": 1991,
    "__1": "NBA",
    "__2": "Chicago Bulls",
    "__3": "Los Angeles Lakers",
    "__4": "M. Jordan",
    "Top Performers": "M. Jordan (529)",
    "Top Performers__1": "D. Rodman (177)",
    "Top Performers__2": "M. Johnson (240)",
    "Top Performers__3": "M. Jordan (4.8)"
  },
  {
    "": 1990,
    "__1": "NBA",
    "__2": "Detroit Pistons",
    "__3": "Portland Trail Blazers",
    "__4": "I. Thomas",
    "Top Performers": "M. Jordan (587)",
    "Top Performers__1": "B. Laimbeer (211)",
    "Top Performers__2": "K. Johnson (170)",
    "Top Performers__3": "M. Jordan (4.0)"
  },
  {
    "": 1989,
    "__1": "NBA",
    "__2": "Detroit Pistons",
    "__3": "Los Angeles Lakers",
    "__4": "J. Dumars",
    "Top Performers": "M. Jordan (591)",
    "Top Performers__1": "D. Rodman (170)",
    "Top Performers__2": "M. Johnson (165)",
    "Top Performers__3": "M. Jordan (4.0)"
  },
  {
    "": 1988,
    "__1": "NBA",
    "__2": "Los Angeles Lakers",
    "__3": "Detroit Pistons",
    "__4": "J. Worthy",
    "Top Performers": "J. Worthy (506)",
    "Top Performers__1": "B. Laimbeer (221)",
    "Top Performers__2": "M. Johnson (303)",
    "Top Performers__3": "M. Johnson (4.0)"
  },
  {
    "": 1987,
    "__1": "NBA",
    "__2": "Los Angeles Lakers",
    "__3": "Boston Celtics",
    "__4": "M. Johnson",
    "Top Performers": "L. Bird (622)",
    "Top Performers__1": "L. Bird (231)",
    "Top Performers__2": "M. Johnson (219)",
    "Top Performers__3": "M. Johnson (3.7)"
  },
  {
    "": 1986,
    "__1": "NBA",
    "__2": "Boston Celtics",
    "__3": "Houston Rockets",
    "__4": "L. Bird",
    "Top Performers": "H. Olajuwon (537)",
    "Top Performers__1": "H. Olajuwon (236)",
    "Top Performers__2": "M. Johnson (211)",
    "Top Performers__3": "L. Bird (4.2)"
  },
  {
    "": 1985,
    "__1": "NBA",
    "__2": "Los Angeles Lakers",
    "__3": "Boston Celtics",
    "__4": "K. Abdul-Jabbar",
    "Top Performers": "L. Bird (520)",
    "Top Performers__1": "R. Parish (219)",
    "Top Performers__2": "M. Johnson (289)",
    "Top Performers__3": "M. Johnson (3.0)"
  },
  {
    "": 1984,
    "__1": "NBA",
    "__2": "Boston Celtics",
    "__3": "Los Angeles Lakers",
    "__4": "L. Bird",
    "Top Performers": "L. Bird (632)",
    "Top Performers__1": "L. Bird (252)",
    "Top Performers__2": "M. Johnson (284)",
    "Top Performers__3": "L. Bird (4.7)"
  },
  {
    "": 1983,
    "__1": "NBA",
    "__2": "Philadelphia 76ers",
    "__3": "Los Angeles Lakers",
    "__4": "M. Malone",
    "Top Performers": "K. Abdul-Jabbar (406)",
    "Top Performers__1": "M. Malone (206)",
    "Top Performers__2": "M. Johnson (192)",
    "Top Performers__3": "M. Malone (2.8)"
  },
  {
    "": 1982,
    "__1": "NBA",
    "__2": "Los Angeles Lakers",
    "__3": "Philadelphia 76ers",
    "__4": "M. Johnson",
    "Top Performers": "J. Erving (461)",
    "Top Performers__1": "C. Jones (189)",
    "Top Performers__2": "M. Cheeks (172)",
    "Top Performers__3": "J. Erving (3.0)"
  },
  {
    "": 1981,
    "__1": "NBA",
    "__2": "Boston Celtics",
    "__3": "Houston Rockets",
    "__4": "C. Maxwell",
    "Top Performers": "M. Malone (562)",
    "Top Performers__1": "M. Malone (305)",
    "Top Performers__2": "M. Cheeks (116)",
    "Top Performers__3": "M. Malone (3.5)"
  },
  {
    "": 1980,
    "__1": "NBA",
    "__2": "Los Angeles Lakers",
    "__3": "Philadelphia 76ers",
    "__4": "M. Johnson",
    "Top Performers": "K. Abdul-Jabbar (479)",
    "Top Performers__1": "C. Jones (185)",
    "Top Performers__2": "M. Johnson (151)",
    "Top Performers__3": "K. Abdul-Jabbar (3.3)"
  },
  {
    "": 1979,
    "__1": "NBA",
    "__2": "Seattle SuperSonics",
    "__3": "Washington Bullets",
    "__4": "D. Johnson",
    "Top Performers": "G. Williams (454)",
    "Top Performers__1": "E. Hayes (266)",
    "Top Performers__2": "T. Henderson (107)",
    "Top Performers__3": "G. Williams (2.7)"
  },
  {
    "": 1978,
    "__1": "NBA",
    "__2": "Washington Bullets",
    "__3": "Seattle SuperSonics",
    "__4": "W. Unseld",
    "Top Performers": "E. Hayes (457)",
    "Top Performers__1": "M. Webster (289)",
    "Top Performers__2": "T. Henderson (106)",
    "Top Performers__3": "E. Hayes (3.1)"
  },
  {
    "": 1977,
    "__1": "NBA",
    "__2": "Portland Trail Blazers",
    "__3": "Philadelphia 76ers",
    "__4": "B. Walton",
    "Top Performers": "J. Erving (518)",
    "Top Performers__1": "B. Walton (288)",
    "Top Performers__2": "B. Walton (104)",
    "Top Performers__3": "J. Erving (3.4)"
  },
  {
    "": 1976,
    "__1": "NBA",
    "__2": "Boston Celtics",
    "__3": "Phoenix Suns",
    "__4": "J. White",
    "Top Performers": "J. White (408)",
    "Top Performers__1": "D. Cowens (296)",
    "Top Performers__2": "A. Adams (98)",
    "Top Performers__3": "D. Cowens (2.7)"
  },
  {
    "": 1976,
    "__1": "ABA",
    "__2": "New York Nets",
    "__3": "Denver Nuggets",
    "__4": "",
    "Top Performers": "J. Erving (451)",
    "Top Performers__1": "J. Erving (164)",
    "Top Performers__2": "L. Dampier (77)",
    "Top Performers__3": "J. Erving (3.7)"
  },
  {
    "": 1975,
    "__1": "NBA",
    "__2": "Golden State Warriors",
    "__3": "Washington Bullets",
    "__4": "R. Barry",
    "Top Performers": "R. Barry (479)",
    "Top Performers__1": "W. Unseld (276)",
    "Top Performers__2": "K. Porter (124)",
    "Top Performers__3": "R. Barry (3.1)"
  },
  {
    "": 1975,
    "__1": "ABA",
    "__2": "Kentucky Colonels",
    "__3": "Indiana Pacers",
    "__4": "",
    "Top Performers": "G. McGinnis (581)",
    "Top Performers__1": "G. McGinnis (286)",
    "Top Performers__2": "G. McGinnis (148)",
    "Top Performers__3": "A. Gilmore (3.0)"
  },
  {
    "": 1974,
    "__1": "NBA",
    "__2": "Boston Celtics",
    "__3": "Milwaukee Bucks",
    "__4": "J. Havlicek",
    "Top Performers": "K. Abdul-Jabbar (515)",
    "Top Performers__1": "K. Abdul-Jabbar (253)",
    "Top Performers__2": "O. Robertson (149)",
    "Top Performers__3": "K. Abdul-Jabbar (4.7)"
  },
  {
    "": 1974,
    "__1": "ABA",
    "__2": "New York Nets",
    "__3": "Utah Stars",
    "__4": "",
    "Top Performers": "W. Wise (420)",
    "Top Performers__1": "G. Govan (246)",
    "Top Performers__2": "R. Boone (109)",
    "Top Performers__3": "J. Erving (3.0)"
  },
  {
    "": 1973,
    "__1": "NBA",
    "__2": "New York Knicks",
    "__3": "Los Angeles Lakers",
    "__4": "W. Reed",
    "Top Performers": "J. West (401)",
    "Top Performers__1": "W. Chamberlain (383)",
    "Top Performers__2": "J. West (132)",
    "Top Performers__3": "W. Frazier (3.0)"
  },
  {
    "": 1973,
    "__1": "ABA",
    "__2": "Indiana Pacers",
    "__3": "Kentucky Colonels",
    "__4": "",
    "Top Performers": "D. Issel (521)",
    "Top Performers__1": "A. Gilmore (260)",
    "Top Performers__2": "F. Lewis (91)",
    "Top Performers__3": "D. Issel (3.6)"
  },
  {
    "": 1972,
    "__1": "NBA",
    "__2": "Los Angeles Lakers",
    "__3": "New York Knicks",
    "__4": "W. Chamberlain",
    "Top Performers": "W. Frazier (388)",
    "Top Performers__1": "W. Chamberlain (315)",
    "Top Performers__2": "J. West (134)",
    "Top Performers__3": "W. Frazier (3.3)"
  },
  {
    "": 1972,
    "__1": "ABA",
    "__2": "Indiana Pacers",
    "__3": "New York Nets",
    "__4": "",
    "Top Performers": "R. Barry (554)",
    "Top Performers__1": "M. Daniels (302)",
    "Top Performers__2": "F. Lewis (87)",
    "Top Performers__3": "J. Erving (2.8)"
  },
  {
    "": 1971,
    "__1": "NBA",
    "__2": "Milwaukee Bucks",
    "__3": "Baltimore Bullets",
    "__4": "K. Abdul-Jabbar",
    "Top Performers": "E. Monroe (397)",
    "Top Performers__1": "W. Unseld (339)",
    "Top Performers__2": "O. Robertson (124)",
    "Top Performers__3": "K. Abdul-Jabbar (3.3)"
  },
  {
    "": 1971,
    "__1": "ABA",
    "__2": "Utah Stars",
    "__3": "Kentucky Colonels",
    "__4": "",
    "Top Performers": "D. Issel (534)",
    "Top Performers__1": "Z. Beaty (263)",
    "Top Performers__2": "L. Dampier (179)",
    "Top Performers__3": "D. Issel (3.3)"
  },
  {
    "": 1970,
    "__1": "NBA",
    "__2": "New York Knicks",
    "__3": "Los Angeles Lakers",
    "__4": "W. Reed",
    "Top Performers": "J. West (562)",
    "Top Performers__1": "W. Chamberlain (399)",
    "Top Performers__2": "W. Frazier (156)",
    "Top Performers__3": "J. West (3.2)"
  },
  {
    "": 1970,
    "__1": "ABA",
    "__2": "Indiana Pacers",
    "__3": "Los Angeles Stars",
    "__4": "",
    "Top Performers": "S. Haywood (440)",
    "Top Performers__1": "M. Daniels (265)",
    "Top Performers__2": "M. Calvin (101)",
    "Top Performers__3": "R. Brown (3.5)"
  },
  {
    "": 1969,
    "__1": "NBA",
    "__2": "Boston Celtics",
    "__3": "Los Angeles Lakers",
    "__4": "J. West",
    "Top Performers": "J. West (556)",
    "Top Performers__1": "W. Chamberlain (444)",
    "Top Performers__2": "J. West (135)",
    "Top Performers__3": "J. West (4.3)"
  },
  {
    "": 1969,
    "__1": "ABA",
    "__2": "Oakland Oaks",
    "__3": "Indiana Pacers",
    "__4": "",
    "Top Performers": "W. Jabali (460)",
    "Top Performers__1": "M. Daniels (237)",
    "Top Performers__2": "L. Brown (87)",
    "Top Performers__3": "R. Brown (3.4)"
  },
  {
    "": 1968,
    "__1": "NBA",
    "__2": "Boston Celtics",
    "__3": "Los Angeles Lakers",
    "__4": "",
    "Top Performers": "J. Havlicek (493)",
    "Top Performers__1": "B. Russell (434)",
    "Top Performers__2": "J. Havlicek (142)",
    "Top Performers__3": "J. West (3.6)"
  },
  {
    "": 1968,
    "__1": "ABA",
    "__2": "Pittsburgh Pipers",
    "__3": "New Orleans Buccaneers",
    "__4": "",
    "Top Performers": "C. Hawkins (419)",
    "Top Performers__1": "T. Washington (261)",
    "Top Performers__2": "L. Brown (129)",
    "Top Performers__3": "C. Hawkins (4.0)"
  },
  {
    "": 1967,
    "__1": "NBA",
    "__2": "Philadelphia 76ers",
    "__3": "San Francisco Warriors",
    "__4": "",
    "Top Performers": "R. Barry (521)",
    "Top Performers__1": "W. Chamberlain (437)",
    "Top Performers__2": "W. Chamberlain (135)",
    "Top Performers__3": "W. Chamberlain (3.8)"
  },
  {
    "": 1966,
    "__1": "NBA",
    "__2": "Boston Celtics",
    "__3": "Los Angeles Lakers",
    "__4": "",
    "Top Performers": "J. West (479)",
    "Top Performers__1": "B. Russell (428)",
    "Top Performers__2": "B. Russell (85)",
    "Top Performers__3": "B. Russell (3.2)"
  },
  {
    "": 1965,
    "__1": "NBA",
    "__2": "Boston Celtics",
    "__3": "Los Angeles Lakers",
    "__4": "",
    "Top Performers": "J. West (447)",
    "Top Performers__1": "B. Russell (302)",
    "Top Performers__2": "B. Russell (76)",
    "Top Performers__3": "B. Russell (3.3)"
  },
  {
    "": 1964,
    "__1": "NBA",
    "__2": "Boston Celtics",
    "__3": "San Francisco Warriors",
    "__4": "",
    "Top Performers": "W. Chamberlain (416)",
    "Top Performers__1": "W. Chamberlain (302)",
    "Top Performers__2": "G. Rodgers (90)",
    "Top Performers__3": "W. Chamberlain (3.8)"
  },
  {
    "": 1963,
    "__1": "NBA",
    "__2": "Boston Celtics",
    "__3": "Los Angeles Lakers",
    "__4": "",
    "Top Performers": "E. Baylor (424)",
    "Top Performers__1": "B. Russell (326)",
    "Top Performers__2": "B. Cousy (116)",
    "Top Performers__3": "B. Russell (2.5)"
  },
  {
    "": 1962,
    "__1": "NBA",
    "__2": "Boston Celtics",
    "__3": "Los Angeles Lakers",
    "__4": "",
    "Top Performers": "E. Baylor (502)",
    "Top Performers__1": "B. Russell (370)",
    "Top Performers__2": "B. Cousy (123)",
    "Top Performers__3": "B. Russell (3.6)"
  },
  {
    "": 1961,
    "__1": "NBA",
    "__2": "Boston Celtics",
    "__3": "St. Louis Hawks",
    "__4": "",
    "Top Performers": "E. Baylor (457)",
    "Top Performers__1": "B. Russell (299)",
    "Top Performers__2": "B. Cousy (91)",
    "Top Performers__3": "E. Baylor (2.8)"
  },
  {
    "": 1960,
    "__1": "NBA",
    "__2": "Boston Celtics",
    "__3": "St. Louis Hawks",
    "__4": "",
    "Top Performers": "B. Pettit (365)",
    "Top Performers__1": "B. Russell (336)",
    "Top Performers__2": "B. Cousy (116)",
    "Top Performers__3": "B. Russell (3.0)"
  },
  {
    "": 1959,
    "__1": "NBA",
    "__2": "Boston Celtics",
    "__3": "Minneapolis Lakers",
    "__4": "",
    "Top Performers": "E. Baylor (331)",
    "Top Performers__1": "B. Russell (305)",
    "Top Performers__2": "B. Cousy (119)",
    "Top Performers__3": "F. Ramsey (2.0)"
  },
  {
    "": 1958,
    "__1": "NBA",
    "__2": "St. Louis Hawks",
    "__3": "Boston Celtics",
    "__4": "",
    "Top Performers": "C. Hagan (305)",
    "Top Performers__1": "B. Russell (221)",
    "Top Performers__2": "B. Cousy (82)",
    "Top Performers__3": "C. Hagan (2.7)"
  },
  {
    "": 1957,
    "__1": "NBA",
    "__2": "Boston Celtics",
    "__3": "St. Louis Hawks",
    "__4": "",
    "Top Performers": "B. Pettit (298)",
    "Top Performers__1": "B. Russell (244)",
    "Top Performers__2": "B. Cousy (93)",
    "Top Performers__3": "B. Pettit (1.7)"
  },
  {
    "": 1956,
    "__1": "NBA",
    "__2": "Philadelphia Warriors",
    "__3": "Fort Wayne Pistons",
    "__4": "",
    "Top Performers": "P. Arizin (289)",
    "Top Performers__1": "N. Johnston (143)",
    "Top Performers__2": "G. King (60)",
    "Top Performers__3": "P. Arizin (2.2)"
  },
  {
    "": 1955,
    "__1": "NBA",
    "__2": "Syracuse Nationals",
    "__3": "Fort Wayne Pistons",
    "__4": "",
    "Top Performers": "D. Schayes (209)",
    "Top Performers__1": "D. Schayes (141)",
    "Top Performers__2": "A. Phillip (78)",
    "Top Performers__3": "D. Schayes (1.8)"
  },
  {
    "": 1954,
    "__1": "NBA",
    "__2": "Minneapolis Lakers",
    "__3": "Syracuse Nationals",
    "__4": "",
    "Top Performers": "G. Mikan (252)",
    "Top Performers__1": "G. Mikan (171)",
    "Top Performers__2": "S. Martin (60)",
    "Top Performers__3": "G. Mikan (3.5)"
  },
  {
    "": 1953,
    "__1": "NBA",
    "__2": "Minneapolis Lakers",
    "__3": "New York Knicks",
    "__4": "",
    "Top Performers": "G. Mikan (238)",
    "Top Performers__1": "G. Mikan (185)",
    "Top Performers__2": "D. McGuire (70)",
    "Top Performers__3": "G. Mikan (2.0)"
  },
  {
    "": 1952,
    "__1": "NBA",
    "__2": "Minneapolis Lakers",
    "__3": "New York Knicks",
    "__4": "",
    "Top Performers": "G. Mikan (307)",
    "Top Performers__1": "G. Mikan (207)",
    "Top Performers__2": "D. McGuire (90)",
    "Top Performers__3": "G. Mikan (2.4)"
  },
  {
    "": 1951,
    "__1": "NBA",
    "__2": "Rochester Royals",
    "__3": "New York Knicks",
    "__4": "",
    "Top Performers": "A. Risen (273)",
    "Top Performers__1": "A. Risen (196)",
    "Top Performers__2": "D. McGuire (78)",
    "Top Performers__3": "B. Wanzer (2.7)"
  },
  {
    "": 1950,
    "__1": "NBA",
    "__2": "Minneapolis Lakers",
    "__3": "Syracuse Nationals",
    "__4": "",
    "Top Performers": "G. Mikan (376)",
    "Top Performers__1": "",
    "Top Performers__2": "J. Pollard (56)",
    "Top Performers__3": "G. Mikan (3.7)"
  },
  {
    "": 1949,
    "__1": "BAA",
    "__2": "Minneapolis Lakers",
    "__3": "Washington Capitols",
    "__4": "",
    "Top Performers": "G. Mikan (303)",
    "Top Performers__1": "",
    "Top Performers__2": "J. Pollard (39)",
    "Top Performers__3": "G. Mikan (4.2)"
  },
  {
    "": 1948,
    "__1": "BAA",
    "__2": "Baltimore Bullets",
    "__3": "Philadelphia Warriors",
    "__4": "",
    "Top Performers": "J. Fulks (282)",
    "Top Performers__1": "",
    "Top Performers__2": "H. Dallmar (37)",
    "Top Performers__3": "C. Simmons (2.5)"
  },
  {
    "": 1947,
    "__1": "BAA",
    "__2": "Philadelphia Warriors",
    "__3": "Chicago Stags",
    "__4": "",
    "Top Performers": "J. Fulks (222)",
    "Top Performers__1": "",
    "Top Performers__2": "H. Dallmar (16)",
    "Top Performers__3": "J. Fulks (2.3)"
  }
]
