
[
  {
    Year: "Year",
    Lg: "Lg",
    Franchise: "Champion",
    Runner_up: "Runner-Up",
    Mvp: "Finals Mvp",
    "Top Performers": "Points",
    "Top Performers__1": "Rebounds",
    "Top Performers__2": "Assists",
    "Top Performers__3": "Win Shares"
  },
  {
    Year: 2019,
    Lg: "NBA",
    Franchise: "Toronto Raptors",
    Runner_up: "Golden State Warriors",
    Mvp: "K. Leonard",
    "Top Performers": "K. Leonard (732)",
    "Top Performers__1": "D. Green (223)",
    "Top Performers__2": "D. Green (187)",
    "Top Performers__3": "K. Leonard (4.9)"
  },
  {
    Year: 2018,
    Lg: "NBA",
    Franchise: "Golden State Warriors",
    Runner_up: "Cleveland Cavaliers",
    Mvp: "K. Durant",
    "Top Performers": "L. James (748)",
    "Top Performers__1": "D. Green (222)",
    "Top Performers__2": "L. James (198)",
    "Top Performers__3": "L. James (5.2)"
  },
  {
    Year: 2017,
    Lg: "NBA",
    Franchise: "Golden State Warriors",
    Runner_up: "Cleveland Cavaliers",
    Mvp: "K. Durant",
    "Top Performers": "L. James (591)",
    "Top Performers__1": "K. Love (191)",
    "Top Performers__2": "L. James (141)",
    "Top Performers__3": "L. James (4.3)"
  },
  {
    Year: 2016,
    Lg: "NBA",
    Franchise: "Cleveland Cavaliers",
    Runner_up: "Golden State Warriors",
    Mvp: "L. James",
    "Top Performers": "K. Thompson (582)",
    "Top Performers__1": "D. Green (228)",
    "Top Performers__2": "R. Westbrook (198)",
    "Top Performers__3": "L. James (4.7)"
  },
  {
    Year: 2015,
    Lg: "NBA",
    Franchise: "Golden State Warriors",
    Runner_up: "Cleveland Cavaliers",
    Mvp: "A. Iguodala",
    "Top Performers": "L. James (601)",
    "Top Performers__1": "D. Howard (238)",
    "Top Performers__2": "L. James (169)",
    "Top Performers__3": "S. Curry (3.9)"
  },
  {
    Year: 2014,
    Lg: "NBA",
    Franchise: "San Antonio Spurs",
    Runner_up: "Miami Heat",
    Mvp: "K. Leonard",
    "Top Performers": "K. Durant (563)",
    "Top Performers__1": "T. Duncan (211)",
    "Top Performers__2": "R. Westbrook (153)",
    "Top Performers__3": "L. James (4.3)"
  },
  {
    Year: 2013,
    Lg: "NBA",
    Franchise: "Miami Heat",
    Runner_up: "San Antonio Spurs",
    Mvp: "L. James",
    "Top Performers": "L. James (596)",
    "Top Performers__1": "T. Duncan (214)",
    "Top Performers__2": "L. James (152)",
    "Top Performers__3": "L. James (5.2)"
  },
  {
    Year: 2012,
    Lg: "NBA",
    Franchise: "Miami Heat",
    Runner_up: "Oklahoma City Thunder",
    Mvp: "L. James",
    "Top Performers": "L. James (697)",
    "Top Performers__1": "L. James (224)",
    "Top Performers__2": "R. Rondo (227)",
    "Top Performers__3": "L. James (5.8)"
  },
  {
    Year: 2011,
    Lg: "NBA",
    Franchise: "Dallas Mavericks",
    Runner_up: "Miami Heat",
    Mvp: "D. Nowitzki",
    "Top Performers": "D. Nowitzki (582)",
    "Top Performers__1": "T. Chandler (193)",
    "Top Performers__2": "J. Kidd (153)",
    "Top Performers__3": "L. James (3.8)"
  },
  {
    Year: 2010,
    Lg: "NBA",
    Franchise: "Los Angeles Lakers",
    Runner_up: "Boston Celtics",
    Mvp: "K. Bryant",
    "Top Performers": "K. Bryant (671)",
    "Top Performers__1": "P. Gasol (255)",
    "Top Performers__2": "R. Rondo (223)",
    "Top Performers__3": "P. Gasol (4.3)"
  },
  {
    Year: 2009,
    Lg: "NBA",
    Franchise: "Los Angeles Lakers",
    Runner_up: "Orlando Magic",
    Mvp: "K. Bryant",
    "Top Performers": "K. Bryant (695)",
    "Top Performers__1": "D. Howard (353)",
    "Top Performers__2": "R. Rondo (137)",
    "Top Performers__3": "L. James (4.8)"
  },
  {
    Year: 2008,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "Los Angeles Lakers",
    Mvp: "P. Pierce",
    "Top Performers": "K. Bryant (633)",
    "Top Performers__1": "K. Garnett (274)",
    "Top Performers__2": "R. Rondo (172)",
    "Top Performers__3": "K. Garnett (4.1)"
  },
  {
    Year: 2007,
    Lg: "NBA",
    Franchise: "San Antonio Spurs",
    Runner_up: "Cleveland Cavaliers",
    Mvp: "T. Parker",
    "Top Performers": "L. James (501)",
    "Top Performers__1": "T. Duncan (229)",
    "Top Performers__2": "L. James (159)",
    "Top Performers__3": "L. James (3.7)"
  },
  {
    Year: 2006,
    Lg: "NBA",
    Franchise: "Miami Heat",
    Runner_up: "Dallas Mavericks",
    Mvp: "D. Wade",
    "Top Performers": "D. Wade (654)",
    "Top Performers__1": "D. Nowitzki (268)",
    "Top Performers__2": "S. Nash (204)",
    "Top Performers__3": "D. Nowitzki (5.4)"
  },
  {
    Year: 2005,
    Lg: "NBA",
    Franchise: "San Antonio Spurs",
    Runner_up: "Detroit Pistons",
    Mvp: "T. Duncan",
    "Top Performers": "T. Duncan (542)",
    "Top Performers__1": "T. Duncan (286)",
    "Top Performers__2": "S. Nash (170)",
    "Top Performers__3": "C. Billups (4.6)"
  },
  {
    Year: 2004,
    Lg: "NBA",
    Franchise: "Detroit Pistons",
    Runner_up: "Los Angeles Lakers",
    Mvp: "C. Billups",
    "Top Performers": "K. Bryant (539)",
    "Top Performers__1": "B. Wallace (328)",
    "Top Performers__2": "C. Billups (136)",
    "Top Performers__3": "S. O'Neal (3.9)"
  },
  {
    Year: 2003,
    Lg: "NBA",
    Franchise: "San Antonio Spurs",
    Runner_up: "New Jersey Nets",
    Mvp: "T. Duncan",
    "Top Performers": "T. Duncan (593)",
    "Top Performers__1": "T. Duncan (369)",
    "Top Performers__2": "J. Kidd (163)",
    "Top Performers__3": "T. Duncan (5.9)"
  },
  {
    Year: 2002,
    Lg: "NBA",
    Franchise: "Los Angeles Lakers",
    Runner_up: "New Jersey Nets",
    Mvp: "S. O'Neal",
    "Top Performers": "S. O'Neal (541)",
    "Top Performers__1": "S. O'Neal (239)",
    "Top Performers__2": "J. Kidd (182)",
    "Top Performers__3": "S. O'Neal (3.8)"
  },
  {
    Year: 2001,
    Lg: "NBA",
    Franchise: "Los Angeles Lakers",
    Runner_up: "Philadelphia 76ers",
    Mvp: "S. O'Neal",
    "Top Performers": "A. Iverson (723)",
    "Top Performers__1": "D. Mutombo (316)",
    "Top Performers__2": "A. Iverson (134)",
    "Top Performers__3": "K. Bryant (3.8)"
  },
  {
    Year: 2000,
    Lg: "NBA",
    Franchise: "Los Angeles Lakers",
    Runner_up: "Indiana Pacers",
    Mvp: "S. O'Neal",
    "Top Performers": "S. O'Neal (707)",
    "Top Performers__1": "S. O'Neal (355)",
    "Top Performers__2": "M. Jackson (178)",
    "Top Performers__3": "S. O'Neal (4.7)"
  },
  {
    Year: 1999,
    Lg: "NBA",
    Franchise: "San Antonio Spurs",
    Runner_up: "New York Knicks",
    Mvp: "T. Duncan",
    "Top Performers": "L. Sprewell (407)",
    "Top Performers__1": "T. Duncan (195)",
    "Top Performers__2": "A. Johnson (126)",
    "Top Performers__3": "T. Duncan (3.7)"
  },
  {
    Year: 1998,
    Lg: "NBA",
    Franchise: "Chicago Bulls",
    Runner_up: "Utah Jazz",
    Mvp: "M. Jordan",
    "Top Performers": "M. Jordan (680)",
    "Top Performers__1": "D. Rodman (248)",
    "Top Performers__2": "J. Stockton (155)",
    "Top Performers__3": "M. Jordan (4.8)"
  },
  {
    Year: 1997,
    Lg: "NBA",
    Franchise: "Chicago Bulls",
    Runner_up: "Utah Jazz",
    Mvp: "M. Jordan",
    "Top Performers": "M. Jordan (590)",
    "Top Performers__1": "K. Malone (228)",
    "Top Performers__2": "J. Stockton (191)",
    "Top Performers__3": "M. Jordan (3.9)"
  },
  {
    Year: 1996,
    Lg: "NBA",
    Franchise: "Chicago Bulls",
    Runner_up: "Seattle SuperSonics",
    Mvp: "M. Jordan",
    "Top Performers": "M. Jordan (552)",
    "Top Performers__1": "D. Rodman (247)",
    "Top Performers__2": "J. Stockton (195)",
    "Top Performers__3": "M. Jordan (4.7)"
  },
  {
    Year: 1995,
    Lg: "NBA",
    Franchise: "Houston Rockets",
    Runner_up: "Orlando Magic",
    Mvp: "H. Olajuwon",
    "Top Performers": "H. Olajuwon (725)",
    "Top Performers__1": "S. O'Neal (250)",
    "Top Performers__2": "A. Hardaway (162)",
    "Top Performers__3": "S. O'Neal (3.0)"
  },
  {
    Year: 1994,
    Lg: "NBA",
    Franchise: "Houston Rockets",
    Runner_up: "New York Knicks",
    Mvp: "H. Olajuwon",
    "Top Performers": "H. Olajuwon (664)",
    "Top Performers__1": "P. Ewing (293)",
    "Top Performers__2": "J. Stockton (157)",
    "Top Performers__3": "H. Olajuwon (4.3)"
  },
  {
    Year: 1993,
    Lg: "NBA",
    Franchise: "Chicago Bulls",
    Runner_up: "Phoenix Suns",
    Mvp: "M. Jordan",
    "Top Performers": "M. Jordan (666)",
    "Top Performers__1": "C. Barkley (326)",
    "Top Performers__2": "K. Johnson (182)",
    "Top Performers__3": "C. Barkley (4.6)"
  },
  {
    Year: 1992,
    Lg: "NBA",
    Franchise: "Chicago Bulls",
    Runner_up: "Portland Trail Blazers",
    Mvp: "M. Jordan",
    "Top Performers": "M. Jordan (759)",
    "Top Performers__1": "H. Grant (194)",
    "Top Performers__2": "J. Stockton (217)",
    "Top Performers__3": "M. Jordan (4.1)"
  },
  {
    Year: 1991,
    Lg: "NBA",
    Franchise: "Chicago Bulls",
    Runner_up: "Los Angeles Lakers",
    Mvp: "M. Jordan",
    "Top Performers": "M. Jordan (529)",
    "Top Performers__1": "D. Rodman (177)",
    "Top Performers__2": "M. Johnson (240)",
    "Top Performers__3": "M. Jordan (4.8)"
  },
  {
    Year: 1990,
    Lg: "NBA",
    Franchise: "Detroit Pistons",
    Runner_up: "Portland Trail Blazers",
    Mvp: "I. Thomas",
    "Top Performers": "M. Jordan (587)",
    "Top Performers__1": "B. Laimbeer (211)",
    "Top Performers__2": "K. Johnson (170)",
    "Top Performers__3": "M. Jordan (4.0)"
  },
  {
    Year: 1989,
    Lg: "NBA",
    Franchise: "Detroit Pistons",
    Runner_up: "Los Angeles Lakers",
    Mvp: "J. Dumars",
    "Top Performers": "M. Jordan (591)",
    "Top Performers__1": "D. Rodman (170)",
    "Top Performers__2": "M. Johnson (165)",
    "Top Performers__3": "M. Jordan (4.0)"
  },
  {
    Year: 1988,
    Lg: "NBA",
    Franchise: "Los Angeles Lakers",
    Runner_up: "Detroit Pistons",
    Mvp: "J. Worthy",
    "Top Performers": "J. Worthy (506)",
    "Top Performers__1": "B. Laimbeer (221)",
    "Top Performers__2": "M. Johnson (303)",
    "Top Performers__3": "M. Johnson (4.0)"
  },
  {
    Year: 1987,
    Lg: "NBA",
    Franchise: "Los Angeles Lakers",
    Runner_up: "Boston Celtics",
    Mvp: "M. Johnson",
    "Top Performers": "L. Bird (622)",
    "Top Performers__1": "L. Bird (231)",
    "Top Performers__2": "M. Johnson (219)",
    "Top Performers__3": "M. Johnson (3.7)"
  },
  {
    Year: 1986,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "Houston Rockets",
    Mvp: "L. Bird",
    "Top Performers": "H. Olajuwon (537)",
    "Top Performers__1": "H. Olajuwon (236)",
    "Top Performers__2": "M. Johnson (211)",
    "Top Performers__3": "L. Bird (4.2)"
  },
  {
    Year: 1985,
    Lg: "NBA",
    Franchise: "Los Angeles Lakers",
    Runner_up: "Boston Celtics",
    Mvp: "K. Abdul-Jabbar",
    "Top Performers": "L. Bird (520)",
    "Top Performers__1": "R. Parish (219)",
    "Top Performers__2": "M. Johnson (289)",
    "Top Performers__3": "M. Johnson (3.0)"
  },
  {
    Year: 1984,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "Los Angeles Lakers",
    Mvp: "L. Bird",
    "Top Performers": "L. Bird (632)",
    "Top Performers__1": "L. Bird (252)",
    "Top Performers__2": "M. Johnson (284)",
    "Top Performers__3": "L. Bird (4.7)"
  },
  {
    Year: 1983,
    Lg: "NBA",
    Franchise: "Philadelphia 76ers",
    Runner_up: "Los Angeles Lakers",
    Mvp: "M. Malone",
    "Top Performers": "K. Abdul-Jabbar (406)",
    "Top Performers__1": "M. Malone (206)",
    "Top Performers__2": "M. Johnson (192)",
    "Top Performers__3": "M. Malone (2.8)"
  },
  {
    Year: 1982,
    Lg: "NBA",
    Franchise: "Los Angeles Lakers",
    Runner_up: "Philadelphia 76ers",
    Mvp: "M. Johnson",
    "Top Performers": "J. Erving (461)",
    "Top Performers__1": "C. Jones (189)",
    "Top Performers__2": "M. Cheeks (172)",
    "Top Performers__3": "J. Erving (3.0)"
  },
  {
    Year: 1981,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "Houston Rockets",
    Mvp: "C. Maxwell",
    "Top Performers": "M. Malone (562)",
    "Top Performers__1": "M. Malone (305)",
    "Top Performers__2": "M. Cheeks (116)",
    "Top Performers__3": "M. Malone (3.5)"
  },
  {
    Year: 1980,
    Lg: "NBA",
    Franchise: "Los Angeles Lakers",
    Runner_up: "Philadelphia 76ers",
    Mvp: "M. Johnson",
    "Top Performers": "K. Abdul-Jabbar (479)",
    "Top Performers__1": "C. Jones (185)",
    "Top Performers__2": "M. Johnson (151)",
    "Top Performers__3": "K. Abdul-Jabbar (3.3)"
  },
  {
    Year: 1979,
    Lg: "NBA",
    Franchise: "Seattle SuperSonics",
    Runner_up: "Washington Bullets",
    Mvp: "D. Johnson",
    "Top Performers": "G. Williams (454)",
    "Top Performers__1": "E. Hayes (266)",
    "Top Performers__2": "T. Henderson (107)",
    "Top Performers__3": "G. Williams (2.7)"
  },
  {
    Year: 1978,
    Lg: "NBA",
    Franchise: "Washington Bullets",
    Runner_up: "Seattle SuperSonics",
    Mvp: "W. Unseld",
    "Top Performers": "E. Hayes (457)",
    "Top Performers__1": "M. Webster (289)",
    "Top Performers__2": "T. Henderson (106)",
    "Top Performers__3": "E. Hayes (3.1)"
  },
  {
    Year: 1977,
    Lg: "NBA",
    Franchise: "Portland Trail Blazers",
    Runner_up: "Philadelphia 76ers",
    Mvp: "B. Walton",
    "Top Performers": "J. Erving (518)",
    "Top Performers__1": "B. Walton (288)",
    "Top Performers__2": "B. Walton (104)",
    "Top Performers__3": "J. Erving (3.4)"
  },
  {
    Year: 1976,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "Phoenix Suns",
    Mvp: "J. White",
    "Top Performers": "J. White (408)",
    "Top Performers__1": "D. Cowens (296)",
    "Top Performers__2": "A. Adams (98)",
    "Top Performers__3": "D. Cowens (2.7)"
  },
  {
    Year: 1975,
    Lg: "NBA",
    Franchise: "Golden State Warriors",
    Runner_up: "Washington Bullets",
    Mvp: "R. Barry",
    "Top Performers": "R. Barry (479)",
    "Top Performers__1": "W. Unseld (276)",
    "Top Performers__2": "K. Porter (124)",
    "Top Performers__3": "R. Barry (3.1)"
  },
  {
    Year: 1974,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "Milwaukee Bucks",
    Mvp: "J. Havlicek",
    "Top Performers": "K. Abdul-Jabbar (515)",
    "Top Performers__1": "K. Abdul-Jabbar (253)",
    "Top Performers__2": "O. Robertson (149)",
    "Top Performers__3": "K. Abdul-Jabbar (4.7)"
  },
  {
    Year: 1973,
    Lg: "NBA",
    Franchise: "New York Knicks",
    Runner_up: "Los Angeles Lakers",
    Mvp: "W. Reed",
    "Top Performers": "J. West (401)",
    "Top Performers__1": "W. Chamberlain (383)",
    "Top Performers__2": "J. West (132)",
    "Top Performers__3": "W. Frazier (3.0)"
  },
  {
    Year: 1972,
    Lg: "NBA",
    Franchise: "Los Angeles Lakers",
    Runner_up: "New York Knicks",
    Mvp: "W. Chamberlain",
    "Top Performers": "W. Frazier (388)",
    "Top Performers__1": "W. Chamberlain (315)",
    "Top Performers__2": "J. West (134)",
    "Top Performers__3": "W. Frazier (3.3)"
  },
  {
    Year: 1971,
    Lg: "NBA",
    Franchise: "Milwaukee Bucks",
    Runner_up: "Baltimore Bullets",
    Mvp: "K. Abdul-Jabbar",
    "Top Performers": "E. Monroe (397)",
    "Top Performers__1": "W. Unseld (339)",
    "Top Performers__2": "O. Robertson (124)",
    "Top Performers__3": "K. Abdul-Jabbar (3.3)"
  },
  {
    Year: 1970,
    Lg: "NBA",
    Franchise: "New York Knicks",
    Runner_up: "Los Angeles Lakers",
    Mvp: "W. Reed",
    "Top Performers": "J. West (562)",
    "Top Performers__1": "W. Chamberlain (399)",
    "Top Performers__2": "W. Frazier (156)",
    "Top Performers__3": "J. West (3.2)"
  },
  {
    Year: 1969,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "Los Angeles Lakers",
    Mvp: "J. West",
    "Top Performers": "J. West (556)",
    "Top Performers__1": "W. Chamberlain (444)",
    "Top Performers__2": "J. West (135)",
    "Top Performers__3": "J. West (4.3)"
  },
  {
    Year: 1968,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "Los Angeles Lakers",
    "Top Performers": "J. Havlicek (493)",
    "Top Performers__1": "B. Russell (434)",
    "Top Performers__2": "J. Havlicek (142)",
    "Top Performers__3": "J. West (3.6)"
  },
  {
    Year: 1967,
    Lg: "NBA",
    Franchise: "Philadelphia 76ers",
    Runner_up: "San Francisco Warriors",
    "Top Performers": "R. Barry (521)",
    "Top Performers__1": "W. Chamberlain (437)",
    "Top Performers__2": "W. Chamberlain (135)",
    "Top Performers__3": "W. Chamberlain (3.8)"
  },
  {
    Year: 1966,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "Los Angeles Lakers",
    "Top Performers": "J. West (479)",
    "Top Performers__1": "B. Russell (428)",
    "Top Performers__2": "B. Russell (85)",
    "Top Performers__3": "B. Russell (3.2)"
  },
  {
    Year: 1965,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "Los Angeles Lakers",
    "Top Performers": "J. West (447)",
    "Top Performers__1": "B. Russell (302)",
    "Top Performers__2": "B. Russell (76)",
    "Top Performers__3": "B. Russell (3.3)"
  },
  {
    Year: 1964,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "San Francisco Warriors",
    "Top Performers": "W. Chamberlain (416)",
    "Top Performers__1": "W. Chamberlain (302)",
    "Top Performers__2": "G. Rodgers (90)",
    "Top Performers__3": "W. Chamberlain (3.8)"
  },
  {
    Year: 1963,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "Los Angeles Lakers",
    "Top Performers": "E. Baylor (424)",
    "Top Performers__1": "B. Russell (326)",
    "Top Performers__2": "B. Cousy (116)",
    "Top Performers__3": "B. Russell (2.5)"
  },
  {
    Year: 1962,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "Los Angeles Lakers",
    "Top Performers": "E. Baylor (502)",
    "Top Performers__1": "B. Russell (370)",
    "Top Performers__2": "B. Cousy (123)",
    "Top Performers__3": "B. Russell (3.6)"
  },
  {
    Year: 1961,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "St. Louis Hawks",
    "Top Performers": "E. Baylor (457)",
    "Top Performers__1": "B. Russell (299)",
    "Top Performers__2": "B. Cousy (91)",
    "Top Performers__3": "E. Baylor (2.8)"
  },
  {
    Year: 1960,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "St. Louis Hawks",
    "Top Performers": "B. Pettit (365)",
    "Top Performers__1": "B. Russell (336)",
    "Top Performers__2": "B. Cousy (116)",
    "Top Performers__3": "B. Russell (3.0)"
  },
  {
    Year: 1959,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "Minneapolis Lakers",
    "Top Performers": "E. Baylor (331)",
    "Top Performers__1": "B. Russell (305)",
    "Top Performers__2": "B. Cousy (119)",
    "Top Performers__3": "F. Ramsey (2.0)"
  },
  {
    Year: 1958,
    Lg: "NBA",
    Franchise: "St. Louis Hawks",
    Runner_up: "Boston Celtics",
    "Top Performers": "C. Hagan (305)",
    "Top Performers__1": "B. Russell (221)",
    "Top Performers__2": "B. Cousy (82)",
    "Top Performers__3": "C. Hagan (2.7)"
  },
  {
    Year: 1957,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "St. Louis Hawks",
    "Top Performers": "B. Pettit (298)",
    "Top Performers__1": "B. Russell (244)",
    "Top Performers__2": "B. Cousy (93)",
    "Top Performers__3": "B. Pettit (1.7)"
  },
  {
    Year: 1956,
    Lg: "NBA",
    Franchise: "Philadelphia Warriors",
    Runner_up: "Fort Wayne Pistons",
    "Top Performers": "P. Arizin (289)",
    "Top Performers__1": "N. Johnston (143)",
    "Top Performers__2": "G. King (60)",
    "Top Performers__3": "P. Arizin (2.2)"
  },
  {
    Year: 1955,
    Lg: "NBA",
    Franchise: "Syracuse Nationals",
    Runner_up: "Fort Wayne Pistons",
    "Top Performers": "D. Schayes (209)",
    "Top Performers__1": "D. Schayes (141)",
    "Top Performers__2": "A. Phillip (78)",
    "Top Performers__3": "D. Schayes (1.8)"
  },
  {
    Year: 1954,
    Lg: "NBA",
    Franchise: "Minneapolis Lakers",
    Runner_up: "Syracuse Nationals",
    "Top Performers": "G. Mikan (252)",
    "Top Performers__1": "G. Mikan (171)",
    "Top Performers__2": "S. Martin (60)",
    "Top Performers__3": "G. Mikan (3.5)"
  },
  {
    Year: 1953,
    Lg: "NBA",
    Franchise: "Minneapolis Lakers",
    Runner_up: "New York Knicks",
    "Top Performers": "G. Mikan (238)",
    "Top Performers__1": "G. Mikan (185)",
    "Top Performers__2": "D. McGuire (70)",
    "Top Performers__3": "G. Mikan (2.0)"
  },
  {
    Year: 1952,
    Lg: "NBA",
    Franchise: "Minneapolis Lakers",
    Runner_up: "New York Knicks",
    "Top Performers": "G. Mikan (307)",
    "Top Performers__1": "G. Mikan (207)",
    "Top Performers__2": "D. McGuire (90)",
    "Top Performers__3": "G. Mikan (2.4)"
  },
  {
    Year: 1951,
    Lg: "NBA",
    Franchise: "Rochester Royals",
    Runner_up: "New York Knicks",
    "Top Performers": "A. Risen (273)",
    "Top Performers__1": "A. Risen (196)",
    "Top Performers__2": "D. McGuire (78)",
    "Top Performers__3": "B. Wanzer (2.7)"
  },
  {
    Year: 1950,
    Lg: "NBA",
    Franchise: "Minneapolis Lakers",
    Runner_up: "Syracuse Nationals",
    "Top Performers": "G. Mikan (376)",
    "Top Performers__1": Year,
    "Top Performers__2": "J. Pollard (56)",
    "Top Performers__3": "G. Mikan (3.7)"
  }
]
