let teamsData = [
  {
    Franchise: "Atlanta Hawks",
    League: "NBA",
    From: "1949-50",
    To: "2019-20",
    Yrs: 71,
    Games: 5599,
    Wins: 2758,
    Losses: 2841,
    Win_Percentage: ".493",
    Plyfs: 46,
    Div: 11,
    Conf: 0,
    Champ: 1
  },
  {
    Franchise: "Boston Celtics",
    Losses: "NBA/BAA",
    From: "1946-47",
    To: "2019-20",
    Yrs: 74,
    Games: 5769,
    Wins: 3408,
    Losses: 2361,
    Win_Percentage: ".591",
    Plyfs: 56,
    Div: 31,
    Conf: 9,
    Champ: 17
  },
  {
    Franchise: "Brooklyn Nets",
    Losses: "NBA/ABA",
    From: "1967-68",
    To: "2019-20",
    Yrs: 53,
    Games: 4267,
    Wins: 1843,
    Losses: 2424,
    Win_Percentage: ".432",
    Plyfs: 27,
    Div: 5,
    Conf: 2,
    Champ: 2
  },
  {
    Franchise: "Charlotte Hornets",
    League: "NBA",
    From: "1988-89",
    To: "2019-20",
    Yrs: 30,
    Games: 2376,
    Wins: 1042,
    Losses: 1334,
    Win_Percentage: ".439",
    Plyfs: 10,
    Div: 0,
    Conf: 0,
    Champ: 0
  },
  {
    Franchise: "Chicago Bulls",
    League: "NBA",
    From: "1966-67",
    To: "2019-20",
    Yrs: 54,
    Games: 4345,
    Wins: 2223,
    Losses: 2122,
    Win_Percentage: ".512",
    Plyfs: 35,
    Div: 9,
    Conf: 6,
    Champ: 6
  },
  {
    Franchise: "Cleveland Cavaliers",
    League: "NBA",
    From: "1970-71",
    To: "2019-20",
    Yrs: 50,
    Games: 4016,
    Wins: 1860,
    Losses: 2156,
    Win_Percentage: ".463",
    Plyfs: 22,
    Div: 7,
    Conf: 5,
    Champ: 1
  },
  {
    Franchise: "Dallas Mavericks",
    League: "NBA",
    From: "1980-81",
    To: "2019-20",
    Yrs: 40,
    Games: 3195,
    Wins: 1600,
    Losses: 1595,
    Win_Percentage: ".501",
    Plyfs: 21,
    Div: 3,
    Conf: 2,
    Champ: 1
  },
  {
    Franchise: "Denver Nuggets",
    Losses: "NBA/ABA",
    From: "1967-68",
    To: "2019-20",
    Yrs: 53,
    Games: 4268,
    Wins: 2148,
    Losses: 2120,
    Win_Percentage: ".503",
    Plyfs: 34,
    Div: 11,
    Conf: 0,
    Champ: 0
  },
  {
    Franchise: "Detroit Pistons",
    Losses: "NBA/BAA",
    From: "1948-49",
    To: "2019-20",
    Yrs: 72,
    Games: 5661,
    Wins: 2750,
    Losses: 2911,
    Win_Percentage: ".486",
    Plyfs: 42,
    Div: 11,
    Conf: 5,
    Champ: 3
  },
  {
    Franchise: "Golden State Warriors",
    League: "NBA",
    From: "1971-72",
    To: "2019-20",
    Yrs: 49,
    Games: 3935,
    Wins: 1894,
    Losses: 2041,
    Win_Percentage: ".481",
    Plyfs: 18,
    Div: 7,
    Conf: 6,
    Champ: 4
  },
  {
    Franchise: "Houston Rockets",
    League: "NBA",
    From: "1967-68",
    To: "2019-20",
    Yrs: 53,
    Games: 4261,
    Wins: 2253,
    Losses: 2008,
    Win_Percentage: ".529",
    Plyfs: 33,
    Div: 7,
    Conf: 4,
    Champ: 2
  },
  {
    Franchise: "Indiana Pacers",
    League: "NBA",
    From: "1976-77",
    To: "2019-20",
    Yrs: 44,
    Games: 3524,
    Wins: 1774,
    Losses: 1750,
    Win_Percentage: ".503",
    Plyfs: 26,
    Div: 6,
    Conf: 1,
    Champ: 0
  },
  {
    Franchise: "Los Angeles Clippers",
    League: "NBA",
    From: "1970-71",
    To: "2019-20",
    Yrs: 50,
    Games: 4017,
    Wins: 1643,
    Losses: 2374,
    Win_Percentage: ".409",
    Plyfs: 14,
    Div: 2,
    Conf: 0,
    Champ: 0
  },
  {
    Franchise: "Los Angeles Lakers",
    League: "NBA",
    From: "1960-61",
    To: "2019-20",
    Yrs: 60,
    Games: 4822,
    Wins: 2912,
    Losses: 1910,
    Win_Percentage: ".604",
    Plyfs: 49,
    Div: 28,
    Conf: 18,
    Champ: 11
  },
  {
    Franchise: "Memphis Grizzlies",
    League: "NBA",
    From: "1995-96",
    To: "2019-20",
    Yrs: 25,
    Games: 1966,
    Wins: 814,
    Losses: 1152,
    Win_Percentage: ".414",
    Plyfs: 10,
    Div: 0,
    Conf: 0,
    Champ: 0
  },
  {
    Franchise: "Miami Heat",
    League: "NBA",
    From: "1988-89",
    To: "2019-20",
    Yrs: 32,
    Games: 2539,
    Wins: 1325,
    Losses: 1214,
    Win_Percentage: ".522",
    Plyfs: 20,
    Div: 13,
    Conf: 5,
    Champ: 3
  },
  {
    Franchise: "Milwaukee Bucks",
    League: "NBA",
    From: "1968-69",
    To: "2019-20",
    Yrs: 52,
    Games: 4180,
    Wins: 2169,
    Losses: 2011,
    Win_Percentage: ".519",
    Plyfs: 31,
    Div: 14,
    Conf: 2,
    Champ: 1
  },
  {
    Franchise: "Minnesota Timberwolves",
    League: "NBA",
    From: "1989-90",
    To: "2019-20",
    Yrs: 31,
    Games: 2458,
    Wins: 976,
    Losses: 1482,
    Win_Percentage: ".397",
    Plyfs: 9,
    Div: 1,
    Conf: 0,
    Champ: 0
  },
  {
    Franchise: "New Orleans Pelicans",
    League: "NBA",
    From: "2002-03",
    To: "2019-20",
    Yrs: 18,
    Games: 1425,
    Wins: 661,
    Losses: 764,
    Win_Percentage: ".464",
    Plyfs: 7,
    Div: 1,
    Conf: 0,
    Champ: 0
  },
  {
    Franchise: "New York Knicks",
    Losses: "NBA/BAA",
    From: "1946-47",
    To: "2019-20",
    Yrs: 74,
    Games: 5768,
    Wins: 2791,
    Losses: 2977,
    Win_Percentage: ".484",
    Plyfs: 42,
    Div: 8,
    Conf: 4,
    Champ: 2
  },
  {
    Franchise: "Oklahoma City Thunder",
    League: "NBA",
    From: "1967-68",
    To: "2019-20",
    Yrs: 53,
    Games: 4263,
    Wins: 2311,
    Losses: 1952,
    Win_Percentage: ".542",
    Plyfs: 31,
    Div: 11,
    Conf: 4,
    Champ: 1
  },
  {
    Franchise: "Orlando Magic",
    League: "NBA",
    From: "1989-90",
    To: "2019-20",
    Yrs: 31,
    Games: 2459,
    Wins: 1179,
    Losses: 1280,
    Win_Percentage: ".479",
    Plyfs: 15,
    Div: 6,
    Conf: 2,
    Champ: 0
  },
  {
    Franchise: "Philadelphia 76ers",
    League: "NBA",
    From: "1949-50",
    To: "2019-20",
    Yrs: 71,
    Games: 5597,
    Wins: 2887,
    Losses: 2710,
    Win_Percentage: ".516",
    Plyfs: 49,
    Div: 11,
    Conf: 5,
    Champ: 3
  },
  {
    Franchise: "Phoenix Suns",
    League: "NBA",
    From: "1968-69",
    To: "2019-20",
    Yrs: 52,
    Games: 4180,
    Wins: 2205,
    Losses: 1975,
    Win_Percentage: ".528",
    Plyfs: 29,
    Div: 6,
    Conf: 2,
    Champ: 0
  },
  {
    Franchise: "Portland Trail Blazers",
    League: "NBA",
    From: "1970-71",
    To: "2019-20",
    Yrs: 50,
    Games: 4017,
    Wins: 2154,
    Losses: 1863,
    Win_Percentage: ".536",
    Plyfs: 35,
    Div: 6,
    Conf: 3,
    Champ: 1
  },
  {
    Franchise: "Sacramento Kings",
    Losses: "NBA/BAA",
    From: "1948-49",
    To: "2019-20",
    Yrs: 72,
    Games: 5660,
    Wins: 2578,
    Losses: 3082,
    Win_Percentage: ".455",
    Plyfs: 29,
    Div: 5,
    Conf: 0,
    Champ: 1
  },
  {
    Franchise: "San Antonio Spurs",
    League: "NBA",
    From: "1976-77",
    To: "2019-20",
    Yrs: 44,
    Games: 3523,
    Wins: 2182,
    Losses: 1341,
    Win_Percentage: ".619",
    Plyfs: 39,
    Div: 22,
    Conf: 6,
    Champ: 5
  },
  {
    Franchise: "Toronto Raptors",
    League: "NBA",
    From: "1995-96",
    To: "2019-20",
    Yrs: 25,
    Games: 1966,
    Wins: 934,
    Losses: 1032,
    Win_Percentage: ".475",
    Plyfs: 11,
    Div: 6,
    Conf: 1,
    Champ: 1
  },
  {
    Franchise: "Utah Jazz",
    League: "NBA",
    From: "1974-75",
    To: "2019-20",
    Yrs: 46,
    Games: 3687,
    Wins: 1996,
    Losses: 1691,
    Win_Percentage: ".541",
    Plyfs: 28,
    Div: 9,
    Conf: 2,
    Champ: 0
  },
  {
    Franchise: "Washington Wizards",
    League: "NBA",
    From: "1961-62",
    To: "2019-20",
    Yrs: 59,
    Games: 4742,
    Wins: 2143,
    Losses: 2599,
    Win_Percentage: ".452",
    Plyfs: 29,
    Div: 8,
    Conf: 4,
    Champ: 1
  }
];

let championsData = [
  {
    Year: 2019,
    Lg: "NBA",
    Franchise: "Toronto Raptors",
    Runner_up: "Golden State Warriors",
    Mvp: "K. Leonard",
    "Top Performers": "K. Leonard (732)",
    "Top Performers__1": "D. Green (223)",
    "Top Performers__2": "D. Green (187)",
    "Top Performers__3": "K. Leonard (4.9)"
  },
  {
    Year: 2018,
    Lg: "NBA",
    Franchise: "Golden State Warriors",
    Runner_up: "Cleveland Cavaliers",
    Mvp: "K. Durant",
    "Top Performers": "L. James (748)",
    "Top Performers__1": "D. Green (222)",
    "Top Performers__2": "L. James (198)",
    "Top Performers__3": "L. James (5.2)"
  },
  {
    Year: 2017,
    Lg: "NBA",
    Franchise: "Golden State Warriors",
    Runner_up: "Cleveland Cavaliers",
    Mvp: "K. Durant",
    "Top Performers": "L. James (591)",
    "Top Performers__1": "K. Love (191)",
    "Top Performers__2": "L. James (141)",
    "Top Performers__3": "L. James (4.3)"
  },
  {
    Year: 2016,
    Lg: "NBA",
    Franchise: "Cleveland Cavaliers",
    Runner_up: "Golden State Warriors",
    Mvp: "L. James",
    "Top Performers": "K. Thompson (582)",
    "Top Performers__1": "D. Green (228)",
    "Top Performers__2": "R. Westbrook (198)",
    "Top Performers__3": "L. James (4.7)"
  },
  {
    Year: 2015,
    Lg: "NBA",
    Franchise: "Golden State Warriors",
    Runner_up: "Cleveland Cavaliers",
    Mvp: "A. Iguodala",
    "Top Performers": "L. James (601)",
    "Top Performers__1": "D. Howard (238)",
    "Top Performers__2": "L. James (169)",
    "Top Performers__3": "S. Curry (3.9)"
  },
  {
    Year: 2014,
    Lg: "NBA",
    Franchise: "San Antonio Spurs",
    Runner_up: "Miami Heat",
    Mvp: "K. Leonard",
    "Top Performers": "K. Durant (563)",
    "Top Performers__1": "T. Duncan (211)",
    "Top Performers__2": "R. Westbrook (153)",
    "Top Performers__3": "L. James (4.3)"
  },
  {
    Year: 2013,
    Lg: "NBA",
    Franchise: "Miami Heat",
    Runner_up: "San Antonio Spurs",
    Mvp: "L. James",
    "Top Performers": "L. James (596)",
    "Top Performers__1": "T. Duncan (214)",
    "Top Performers__2": "L. James (152)",
    "Top Performers__3": "L. James (5.2)"
  },
  {
    Year: 2012,
    Lg: "NBA",
    Franchise: "Miami Heat",
    Runner_up: "Oklahoma City Thunder",
    Mvp: "L. James",
    "Top Performers": "L. James (697)",
    "Top Performers__1": "L. James (224)",
    "Top Performers__2": "R. Rondo (227)",
    "Top Performers__3": "L. James (5.8)"
  },
  {
    Year: 2011,
    Lg: "NBA",
    Franchise: "Dallas Mavericks",
    Runner_up: "Miami Heat",
    Mvp: "D. Nowitzki",
    "Top Performers": "D. Nowitzki (582)",
    "Top Performers__1": "T. Chandler (193)",
    "Top Performers__2": "J. Kidd (153)",
    "Top Performers__3": "L. James (3.8)"
  },
  {
    Year: 2010,
    Lg: "NBA",
    Franchise: "Los Angeles Lakers",
    Runner_up: "Boston Celtics",
    Mvp: "K. Bryant",
    "Top Performers": "K. Bryant (671)",
    "Top Performers__1": "P. Gasol (255)",
    "Top Performers__2": "R. Rondo (223)",
    "Top Performers__3": "P. Gasol (4.3)"
  },
  {
    Year: 2009,
    Lg: "NBA",
    Franchise: "Los Angeles Lakers",
    Runner_up: "Orlando Magic",
    Mvp: "K. Bryant",
    "Top Performers": "K. Bryant (695)",
    "Top Performers__1": "D. Howard (353)",
    "Top Performers__2": "R. Rondo (137)",
    "Top Performers__3": "L. James (4.8)"
  },
  {
    Year: 2008,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "Los Angeles Lakers",
    Mvp: "P. Pierce",
    "Top Performers": "K. Bryant (633)",
    "Top Performers__1": "K. Garnett (274)",
    "Top Performers__2": "R. Rondo (172)",
    "Top Performers__3": "K. Garnett (4.1)"
  },
  {
    Year: 2007,
    Lg: "NBA",
    Franchise: "San Antonio Spurs",
    Runner_up: "Cleveland Cavaliers",
    Mvp: "T. Parker",
    "Top Performers": "L. James (501)",
    "Top Performers__1": "T. Duncan (229)",
    "Top Performers__2": "L. James (159)",
    "Top Performers__3": "L. James (3.7)"
  },
  {
    Year: 2006,
    Lg: "NBA",
    Franchise: "Miami Heat",
    Runner_up: "Dallas Mavericks",
    Mvp: "D. Wade",
    "Top Performers": "D. Wade (654)",
    "Top Performers__1": "D. Nowitzki (268)",
    "Top Performers__2": "S. Nash (204)",
    "Top Performers__3": "D. Nowitzki (5.4)"
  },
  {
    Year: 2005,
    Lg: "NBA",
    Franchise: "San Antonio Spurs",
    Runner_up: "Detroit Pistons",
    Mvp: "T. Duncan",
    "Top Performers": "T. Duncan (542)",
    "Top Performers__1": "T. Duncan (286)",
    "Top Performers__2": "S. Nash (170)",
    "Top Performers__3": "C. Billups (4.6)"
  },
  {
    Year: 2004,
    Lg: "NBA",
    Franchise: "Detroit Pistons",
    Runner_up: "Los Angeles Lakers",
    Mvp: "C. Billups",
    "Top Performers": "K. Bryant (539)",
    "Top Performers__1": "B. Wallace (328)",
    "Top Performers__2": "C. Billups (136)",
    "Top Performers__3": "S. O'Neal (3.9)"
  },
  {
    Year: 2003,
    Lg: "NBA",
    Franchise: "San Antonio Spurs",
    Runner_up: "New Jersey Nets",
    Mvp: "T. Duncan",
    "Top Performers": "T. Duncan (593)",
    "Top Performers__1": "T. Duncan (369)",
    "Top Performers__2": "J. Kidd (163)",
    "Top Performers__3": "T. Duncan (5.9)"
  },
  {
    Year: 2002,
    Lg: "NBA",
    Franchise: "Los Angeles Lakers",
    Runner_up: "New Jersey Nets",
    Mvp: "S. O'Neal",
    "Top Performers": "S. O'Neal (541)",
    "Top Performers__1": "S. O'Neal (239)",
    "Top Performers__2": "J. Kidd (182)",
    "Top Performers__3": "S. O'Neal (3.8)"
  },
  {
    Year: 2001,
    Lg: "NBA",
    Franchise: "Los Angeles Lakers",
    Runner_up: "Philadelphia 76ers",
    Mvp: "S. O'Neal",
    "Top Performers": "A. Iverson (723)",
    "Top Performers__1": "D. Mutombo (316)",
    "Top Performers__2": "A. Iverson (134)",
    "Top Performers__3": "K. Bryant (3.8)"
  },
  {
    Year: 2000,
    Lg: "NBA",
    Franchise: "Los Angeles Lakers",
    Runner_up: "Indiana Pacers",
    Mvp: "S. O'Neal",
    "Top Performers": "S. O'Neal (707)",
    "Top Performers__1": "S. O'Neal (355)",
    "Top Performers__2": "M. Jackson (178)",
    "Top Performers__3": "S. O'Neal (4.7)"
  },
  {
    Year: 1999,
    Lg: "NBA",
    Franchise: "San Antonio Spurs",
    Runner_up: "New York Knicks",
    Mvp: "T. Duncan",
    "Top Performers": "L. Sprewell (407)",
    "Top Performers__1": "T. Duncan (195)",
    "Top Performers__2": "A. Johnson (126)",
    "Top Performers__3": "T. Duncan (3.7)"
  },
  {
    Year: 1998,
    Lg: "NBA",
    Franchise: "Chicago Bulls",
    Runner_up: "Utah Jazz",
    Mvp: "M. Jordan",
    "Top Performers": "M. Jordan (680)",
    "Top Performers__1": "D. Rodman (248)",
    "Top Performers__2": "J. Stockton (155)",
    "Top Performers__3": "M. Jordan (4.8)"
  },
  {
    Year: 1997,
    Lg: "NBA",
    Franchise: "Chicago Bulls",
    Runner_up: "Utah Jazz",
    Mvp: "M. Jordan",
    "Top Performers": "M. Jordan (590)",
    "Top Performers__1": "K. Malone (228)",
    "Top Performers__2": "J. Stockton (191)",
    "Top Performers__3": "M. Jordan (3.9)"
  },
  {
    Year: 1996,
    Lg: "NBA",
    Franchise: "Chicago Bulls",
    Runner_up: "Seattle SuperSonics",
    Mvp: "M. Jordan",
    "Top Performers": "M. Jordan (552)",
    "Top Performers__1": "D. Rodman (247)",
    "Top Performers__2": "J. Stockton (195)",
    "Top Performers__3": "M. Jordan (4.7)"
  },
  {
    Year: 1995,
    Lg: "NBA",
    Franchise: "Houston Rockets",
    Runner_up: "Orlando Magic",
    Mvp: "H. Olajuwon",
    "Top Performers": "H. Olajuwon (725)",
    "Top Performers__1": "S. O'Neal (250)",
    "Top Performers__2": "A. Hardaway (162)",
    "Top Performers__3": "S. O'Neal (3.0)"
  },
  {
    Year: 1994,
    Lg: "NBA",
    Franchise: "Houston Rockets",
    Runner_up: "New York Knicks",
    Mvp: "H. Olajuwon",
    "Top Performers": "H. Olajuwon (664)",
    "Top Performers__1": "P. Ewing (293)",
    "Top Performers__2": "J. Stockton (157)",
    "Top Performers__3": "H. Olajuwon (4.3)"
  },
  {
    Year: 1993,
    Lg: "NBA",
    Franchise: "Chicago Bulls",
    Runner_up: "Phoenix Suns",
    Mvp: "M. Jordan",
    "Top Performers": "M. Jordan (666)",
    "Top Performers__1": "C. Barkley (326)",
    "Top Performers__2": "K. Johnson (182)",
    "Top Performers__3": "C. Barkley (4.6)"
  },
  {
    Year: 1992,
    Lg: "NBA",
    Franchise: "Chicago Bulls",
    Runner_up: "Portland Trail Blazers",
    Mvp: "M. Jordan",
    "Top Performers": "M. Jordan (759)",
    "Top Performers__1": "H. Grant (194)",
    "Top Performers__2": "J. Stockton (217)",
    "Top Performers__3": "M. Jordan (4.1)"
  },
  {
    Year: 1991,
    Lg: "NBA",
    Franchise: "Chicago Bulls",
    Runner_up: "Los Angeles Lakers",
    Mvp: "M. Jordan",
    "Top Performers": "M. Jordan (529)",
    "Top Performers__1": "D. Rodman (177)",
    "Top Performers__2": "M. Johnson (240)",
    "Top Performers__3": "M. Jordan (4.8)"
  },
  {
    Year: 1990,
    Lg: "NBA",
    Franchise: "Detroit Pistons",
    Runner_up: "Portland Trail Blazers",
    Mvp: "I. Thomas",
    "Top Performers": "M. Jordan (587)",
    "Top Performers__1": "B. Laimbeer (211)",
    "Top Performers__2": "K. Johnson (170)",
    "Top Performers__3": "M. Jordan (4.0)"
  },
  {
    Year: 1989,
    Lg: "NBA",
    Franchise: "Detroit Pistons",
    Runner_up: "Los Angeles Lakers",
    Mvp: "J. Dumars",
    "Top Performers": "M. Jordan (591)",
    "Top Performers__1": "D. Rodman (170)",
    "Top Performers__2": "M. Johnson (165)",
    "Top Performers__3": "M. Jordan (4.0)"
  },
  {
    Year: 1988,
    Lg: "NBA",
    Franchise: "Los Angeles Lakers",
    Runner_up: "Detroit Pistons",
    Mvp: "J. Worthy",
    "Top Performers": "J. Worthy (506)",
    "Top Performers__1": "B. Laimbeer (221)",
    "Top Performers__2": "M. Johnson (303)",
    "Top Performers__3": "M. Johnson (4.0)"
  },
  {
    Year: 1987,
    Lg: "NBA",
    Franchise: "Los Angeles Lakers",
    Runner_up: "Boston Celtics",
    Mvp: "M. Johnson",
    "Top Performers": "L. Bird (622)",
    "Top Performers__1": "L. Bird (231)",
    "Top Performers__2": "M. Johnson (219)",
    "Top Performers__3": "M. Johnson (3.7)"
  },
  {
    Year: 1986,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "Houston Rockets",
    Mvp: "L. Bird",
    "Top Performers": "H. Olajuwon (537)",
    "Top Performers__1": "H. Olajuwon (236)",
    "Top Performers__2": "M. Johnson (211)",
    "Top Performers__3": "L. Bird (4.2)"
  },
  {
    Year: 1985,
    Lg: "NBA",
    Franchise: "Los Angeles Lakers",
    Runner_up: "Boston Celtics",
    Mvp: "K. Abdul-Jabbar",
    "Top Performers": "L. Bird (520)",
    "Top Performers__1": "R. Parish (219)",
    "Top Performers__2": "M. Johnson (289)",
    "Top Performers__3": "M. Johnson (3.0)"
  },
  {
    Year: 1984,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "Los Angeles Lakers",
    Mvp: "L. Bird",
    "Top Performers": "L. Bird (632)",
    "Top Performers__1": "L. Bird (252)",
    "Top Performers__2": "M. Johnson (284)",
    "Top Performers__3": "L. Bird (4.7)"
  },
  {
    Year: 1983,
    Lg: "NBA",
    Franchise: "Philadelphia 76ers",
    Runner_up: "Los Angeles Lakers",
    Mvp: "M. Malone",
    "Top Performers": "K. Abdul-Jabbar (406)",
    "Top Performers__1": "M. Malone (206)",
    "Top Performers__2": "M. Johnson (192)",
    "Top Performers__3": "M. Malone (2.8)"
  },
  {
    Year: 1982,
    Lg: "NBA",
    Franchise: "Los Angeles Lakers",
    Runner_up: "Philadelphia 76ers",
    Mvp: "M. Johnson",
    "Top Performers": "J. Erving (461)",
    "Top Performers__1": "C. Jones (189)",
    "Top Performers__2": "M. Cheeks (172)",
    "Top Performers__3": "J. Erving (3.0)"
  },
  {
    Year: 1981,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "Houston Rockets",
    Mvp: "C. Maxwell",
    "Top Performers": "M. Malone (562)",
    "Top Performers__1": "M. Malone (305)",
    "Top Performers__2": "M. Cheeks (116)",
    "Top Performers__3": "M. Malone (3.5)"
  },
  {
    Year: 1980,
    Lg: "NBA",
    Franchise: "Los Angeles Lakers",
    Runner_up: "Philadelphia 76ers",
    Mvp: "M. Johnson",
    "Top Performers": "K. Abdul-Jabbar (479)",
    "Top Performers__1": "C. Jones (185)",
    "Top Performers__2": "M. Johnson (151)",
    "Top Performers__3": "K. Abdul-Jabbar (3.3)"
  },
  {
    Year: 1979,
    Lg: "NBA",
    Franchise: "Seattle SuperSonics",
    Runner_up: "Washington Bullets",
    Mvp: "D. Johnson",
    "Top Performers": "G. Williams (454)",
    "Top Performers__1": "E. Hayes (266)",
    "Top Performers__2": "T. Henderson (107)",
    "Top Performers__3": "G. Williams (2.7)"
  },
  {
    Year: 1978,
    Lg: "NBA",
    Franchise: "Washington Bullets",
    Runner_up: "Seattle SuperSonics",
    Mvp: "W. Unseld",
    "Top Performers": "E. Hayes (457)",
    "Top Performers__1": "M. Webster (289)",
    "Top Performers__2": "T. Henderson (106)",
    "Top Performers__3": "E. Hayes (3.1)"
  },
  {
    Year: 1977,
    Lg: "NBA",
    Franchise: "Portland Trail Blazers",
    Runner_up: "Philadelphia 76ers",
    Mvp: "B. Walton",
    "Top Performers": "J. Erving (518)",
    "Top Performers__1": "B. Walton (288)",
    "Top Performers__2": "B. Walton (104)",
    "Top Performers__3": "J. Erving (3.4)"
  },
  {
    Year: 1976,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "Phoenix Suns",
    Mvp: "J. White",
    "Top Performers": "J. White (408)",
    "Top Performers__1": "D. Cowens (296)",
    "Top Performers__2": "A. Adams (98)",
    "Top Performers__3": "D. Cowens (2.7)"
  },
  {
    Year: 1975,
    Lg: "NBA",
    Franchise: "Golden State Warriors",
    Runner_up: "Washington Bullets",
    Mvp: "R. Barry",
    "Top Performers": "R. Barry (479)",
    "Top Performers__1": "W. Unseld (276)",
    "Top Performers__2": "K. Porter (124)",
    "Top Performers__3": "R. Barry (3.1)"
  },
  {
    Year: 1974,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "Milwaukee Bucks",
    Mvp: "J. Havlicek",
    "Top Performers": "K. Abdul-Jabbar (515)",
    "Top Performers__1": "K. Abdul-Jabbar (253)",
    "Top Performers__2": "O. Robertson (149)",
    "Top Performers__3": "K. Abdul-Jabbar (4.7)"
  },
  {
    Year: 1973,
    Lg: "NBA",
    Franchise: "New York Knicks",
    Runner_up: "Los Angeles Lakers",
    Mvp: "W. Reed",
    "Top Performers": "J. West (401)",
    "Top Performers__1": "W. Chamberlain (383)",
    "Top Performers__2": "J. West (132)",
    "Top Performers__3": "W. Frazier (3.0)"
  },
  {
    Year: 1972,
    Lg: "NBA",
    Franchise: "Los Angeles Lakers",
    Runner_up: "New York Knicks",
    Mvp: "W. Chamberlain",
    "Top Performers": "W. Frazier (388)",
    "Top Performers__1": "W. Chamberlain (315)",
    "Top Performers__2": "J. West (134)",
    "Top Performers__3": "W. Frazier (3.3)"
  },
  {
    Year: 1971,
    Lg: "NBA",
    Franchise: "Milwaukee Bucks",
    Runner_up: "Baltimore Bullets",
    Mvp: "K. Abdul-Jabbar",
    "Top Performers": "E. Monroe (397)",
    "Top Performers__1": "W. Unseld (339)",
    "Top Performers__2": "O. Robertson (124)",
    "Top Performers__3": "K. Abdul-Jabbar (3.3)"
  },
  {
    Year: 1970,
    Lg: "NBA",
    Franchise: "New York Knicks",
    Runner_up: "Los Angeles Lakers",
    Mvp: "W. Reed",
    "Top Performers": "J. West (562)",
    "Top Performers__1": "W. Chamberlain (399)",
    "Top Performers__2": "W. Frazier (156)",
    "Top Performers__3": "J. West (3.2)"
  },
  {
    Year: 1969,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "Los Angeles Lakers",
    Mvp: "J. West",
    "Top Performers": "J. West (556)",
    "Top Performers__1": "W. Chamberlain (444)",
    "Top Performers__2": "J. West (135)",
    "Top Performers__3": "J. West (4.3)"
  },
  {
    Year: 1968,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "Los Angeles Lakers",
    "Top Performers": "J. Havlicek (493)",
    "Top Performers__1": "B. Russell (434)",
    "Top Performers__2": "J. Havlicek (142)",
    "Top Performers__3": "J. West (3.6)"
  },
  {
    Year: 1967,
    Lg: "NBA",
    Franchise: "Philadelphia 76ers",
    Runner_up: "San Francisco Warriors",
    "Top Performers": "R. Barry (521)",
    "Top Performers__1": "W. Chamberlain (437)",
    "Top Performers__2": "W. Chamberlain (135)",
    "Top Performers__3": "W. Chamberlain (3.8)"
  },
  {
    Year: 1966,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "Los Angeles Lakers",
    "Top Performers": "J. West (479)",
    "Top Performers__1": "B. Russell (428)",
    "Top Performers__2": "B. Russell (85)",
    "Top Performers__3": "B. Russell (3.2)"
  },
  {
    Year: 1965,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "Los Angeles Lakers",
    "Top Performers": "J. West (447)",
    "Top Performers__1": "B. Russell (302)",
    "Top Performers__2": "B. Russell (76)",
    "Top Performers__3": "B. Russell (3.3)"
  },
  {
    Year: 1964,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "San Francisco Warriors",
    "Top Performers": "W. Chamberlain (416)",
    "Top Performers__1": "W. Chamberlain (302)",
    "Top Performers__2": "G. Rodgers (90)",
    "Top Performers__3": "W. Chamberlain (3.8)"
  },
  {
    Year: 1963,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "Los Angeles Lakers",
    "Top Performers": "E. Baylor (424)",
    "Top Performers__1": "B. Russell (326)",
    "Top Performers__2": "B. Cousy (116)",
    "Top Performers__3": "B. Russell (2.5)"
  },
  {
    Year: 1962,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "Los Angeles Lakers",
    "Top Performers": "E. Baylor (502)",
    "Top Performers__1": "B. Russell (370)",
    "Top Performers__2": "B. Cousy (123)",
    "Top Performers__3": "B. Russell (3.6)"
  },
  {
    Year: 1961,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "St. Louis Hawks",
    "Top Performers": "E. Baylor (457)",
    "Top Performers__1": "B. Russell (299)",
    "Top Performers__2": "B. Cousy (91)",
    "Top Performers__3": "E. Baylor (2.8)"
  },
  {
    Year: 1960,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "St. Louis Hawks",
    "Top Performers": "B. Pettit (365)",
    "Top Performers__1": "B. Russell (336)",
    "Top Performers__2": "B. Cousy (116)",
    "Top Performers__3": "B. Russell (3.0)"
  },
  {
    Year: 1959,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "Minneapolis Lakers",
    "Top Performers": "E. Baylor (331)",
    "Top Performers__1": "B. Russell (305)",
    "Top Performers__2": "B. Cousy (119)",
    "Top Performers__3": "F. Ramsey (2.0)"
  },
  {
    Year: 1958,
    Lg: "NBA",
    Franchise: "St. Louis Hawks",
    Runner_up: "Boston Celtics",
    "Top Performers": "C. Hagan (305)",
    "Top Performers__1": "B. Russell (221)",
    "Top Performers__2": "B. Cousy (82)",
    "Top Performers__3": "C. Hagan (2.7)"
  },
  {
    Year: 1957,
    Lg: "NBA",
    Franchise: "Boston Celtics",
    Runner_up: "St. Louis Hawks",
    "Top Performers": "B. Pettit (298)",
    "Top Performers__1": "B. Russell (244)",
    "Top Performers__2": "B. Cousy (93)",
    "Top Performers__3": "B. Pettit (1.7)"
  },
  {
    Year: 1956,
    Lg: "NBA",
    Franchise: "Philadelphia Warriors",
    Runner_up: "Fort Wayne Pistons",
    "Top Performers": "P. Arizin (289)",
    "Top Performers__1": "N. Johnston (143)",
    "Top Performers__2": "G. King (60)",
    "Top Performers__3": "P. Arizin (2.2)"
  },
  {
    Year: 1955,
    Lg: "NBA",
    Franchise: "Syracuse Nationals",
    Runner_up: "Fort Wayne Pistons",
    "Top Performers": "D. Schayes (209)",
    "Top Performers__1": "D. Schayes (141)",
    "Top Performers__2": "A. Phillip (78)",
    "Top Performers__3": "D. Schayes (1.8)"
  },
  {
    Year: 1954,
    Lg: "NBA",
    Franchise: "Minneapolis Lakers",
    Runner_up: "Syracuse Nationals",
    "Top Performers": "G. Mikan (252)",
    "Top Performers__1": "G. Mikan (171)",
    "Top Performers__2": "S. Martin (60)",
    "Top Performers__3": "G. Mikan (3.5)"
  },
  {
    Year: 1953,
    Lg: "NBA",
    Franchise: "Minneapolis Lakers",
    Runner_up: "New York Knicks",
    "Top Performers": "G. Mikan (238)",
    "Top Performers__1": "G. Mikan (185)",
    "Top Performers__2": "D. McGuire (70)",
    "Top Performers__3": "G. Mikan (2.0)"
  },
  {
    Year: 1952,
    Lg: "NBA",
    Franchise: "Minneapolis Lakers",
    Runner_up: "New York Knicks",
    "Top Performers": "G. Mikan (307)",
    "Top Performers__1": "G. Mikan (207)",
    "Top Performers__2": "D. McGuire (90)",
    "Top Performers__3": "G. Mikan (2.4)"
  },
  {
    Year: 1951,
    Lg: "NBA",
    Franchise: "Rochester Royals",
    Runner_up: "New York Knicks",
    "Top Performers": "A. Risen (273)",
    "Top Performers__1": "A. Risen (196)",
    "Top Performers__2": "D. McGuire (78)",
    "Top Performers__3": "B. Wanzer (2.7)"
  },
  {
    Year: 1950,
    Lg: "NBA",
    Franchise: "Minneapolis Lakers",
    Runner_up: "Syracuse Nationals",
    "Top Performers": "G. Mikan (376)",
    "Top Performers__1": Year,
    "Top Performers__2": "J. Pollard (56)",
    "Top Performers__3": "G. Mikan (3.7)"
  }
];


module.exports = teamsData;
module.exports = championsData;
